Criação do Modal da home
eupedrorodrigues/ImoFind pull request #12
Opened 2023-05-25 23:48 UTC by Guilherme-Sant

2023-05-25 23:54 UTC, Juliocoi requested changes
Comitar novamente para entrar a pasta pages. Retirar do git ignore

2023-05-26 00:03 UTC, Juliocoi approved these changes

2023-05-26 00:04 UTC, Juliocoi approved these changes

2023-05-26 00:05 UTC, Juliocoi approved these changes

2023-05-26 00:05 UTC, Juliocoi approved these changes

2023-05-26 00:12 UTC, Juliocoi approved these changes

2023-05-26 00:14 UTC, Juliocoi approved these changes

2023-05-26 00:16 UTC, Juliocoi approved these changes

2023-05-26 00:17 UTC, eupedrorodrigues approved these changes

2023-05-26 00:19 UTC, eupedrorodrigues approved these changes

2023-05-26 00:19 UTC, eupedrorodrigues approved these changes

2023-05-26 00:20 UTC, Juliocoi approved these changes

2023-05-26 00:28 UTC, closed without merging